### PR TITLE
Add Extended Kalman Filter

### PR DESCRIPTION
**Pull request by pietroglyph**
Finally! If you:
 * Aren't enough of a [megachad](https://github.com/calcmogul) to navigate the byzantine linking system, hairy template errors, and long build times of C++.
 * [Aren't a rational enough person to write your own implementation in a language that doesn't lack basic features like operator overloading, easy functor definitions, and typedefs,](https://gist.github.com/Redrield/348ee5bdb87465bd0b2b73a348c9e736) or too lazy to add the Kotlin runtime as a dependency.
 * Are a masochist.

You can rejoice! A mostly done* EKF implementation in Java is here for your immediate (ish) use!!1
\* tests coming soon (tm).

But seriously, I need to add unit tests. I'll probably do that tomorrow and then mark this as ready.

### CODE REVIEW

**Comment by mcm001** [comment]
You should be able to just uncomment the @Test in the current EKF tests, or just yeet them from C++.

**Comment by pietroglyph** [comment]
Uh... Am I blind @mcm001? I don't see any current Java EKF tests?

**Comment by mcm001** [comment]
Sorry, UKF java test?

**Comment by pietroglyph** [comment]
Tests are written but I still need to plot the data to see if it's sane.

**Pull request merged**
